### ISSUE TITLE
Hospital Data Scraper is Broken

### ISSUE THREAD

**Issue by Mr0grog** [sfbrigade/data-covid19-sfbayarea#187]
The hospital scraper has apparently been broken for a while, but there's no logging. (Will file a different issue for that: https://github.com/sfbrigade/stop-covid19-sfbayarea/issues/1024)

Current error:

```
Hospitalization data fetch encountered error: CKAN API Error: Not found: Resource "42d33765-20fd-44b8-a978-b083b7542225" was not found. (status: 404)
Traceback (most recent call last):
  File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/scraper_hospital_data.py", line 43, in main
    out = hospitals.get_timeseries(ca_counties.bay_area_counties)
  File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/covid19_sfbayarea/data/hospitals.py", line 142, in get_timeseries
    meta = next(data_raw)
  File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/covid19_sfbayarea/data/ckan.py", line 50, in data
    data = self.request(next_url, params=next_params)
  File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/covid19_sfbayarea/data/ckan.py", line 89, in request
    raise BadRequest(f'CKAN API Error: {message}', response=response)
covid19_sfbayarea.data.errors.BadRequest: CKAN API Error: Not found: Resource "42d33765-20fd-44b8-a978-b083b7542225" was not found. (status: 404)
```

See full action logs: https://github.com/sfbrigade/stop-covid19-sfbayarea/runs/2107127471?check_suite_focus=true

/cc @benghancock

**Comment by benghancock** [comment]
Thanks for flagging this @Mr0grog! I'll plan to take a look at this tomorrow.
